name: CI
on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build project with Maven
        run: mvn -B package --file pom.xml

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Container image
        run: docker build -t ${{ secrets.DOCKER_REPO }}:latest .

      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_REPO }}
